### ISSUE TITLE
Missing file: tools/pbomanager/src/resources.c

### ISSUE THREAD

**Issue by blizzard4591** [StidOfficial/libpbo#3]
Hi,
I was trying to use libpbo on Windows 10 with Visual Studio 2019 and CMake, but when configuring with CMake, I get this:
```
CMake Error at CMakeLists.txt:42 (add_executable):
  Cannot find source file:

    tools/pbomanager/src/resources.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:42 (add_executable):
  No SOURCES given to target: pbomanager
```
This file is not part of the sources in this repository.
Any idea?

**Comment by StidOfficial** [comment]
The resources.c is generated by glib-compile-resources command in line 63 in CMakeLists.txt file.

You have probably error with glib-compile-resources command.

I doesn't have test it on Windows at this moment with pbomanager.

You have probably GTKmm dependency not found.

**Comment by StidOfficial** [comment]
Fix :
https://github.com/StidOfficial/libpbo/commit/8d63ea0bb7515c2ba62fcdbfa53093f1f8fa54b5
https://github.com/StidOfficial/libpbo/commit/5dd08466bdb479dbde20ce9bbe0bcc1d399ce677
