### ISSUE TITLE
Fails to build on linux

### ISSUE THREAD

**Issue by shiona** [StidOfficial/libpbo#5]
It looks like cmake does not respect `set(CMAKE_CXX_STANDARD 17)`
Without any modifications the error is about uintX_t not naming a type. If I try to add `#include <cstdint>` or `<stdint.h>` the error changes to `#error this file requires compiler and library support for the iso c++ 2011 standard.`.

I managed to get a build done by adding `-std=c++17` in the `add_definitions` list in the `elseif(CMAKE_COMPILER_IS_GNUCXX)` block. I'm not sure if this is a correct way to solve this.

Using:
c++ (GCC) 11.1.0
cmake version 3.22.1

**Comment by StidOfficial** [comment]
Normally the last commit fixed that, i tested on debian sid.

**Comment by shiona** [comment]
Yup, seems to work now. Thanks.
